# crane.toml

[[nodes]]
name = "vps1"
public_ip = "10.0.0.11"
internal_ip = "10.0.0.11"
roles = ["app", "haproxy", "postgres", "redis"]
user = "crane"
ssh_ip = "127.0.0.1"
ssh_port = 2221
private_key = "keys/id_ed25519"
sudo_pass = "${SUDO_PASS_VPS1}"


[[users]]
name = "deployman"
groups = ["www"]
ssh_authorized_keys = ["keys/id_ed25519.pub"]
private_key = "keys/id_ed25519"

[app.myapp]
name = "myapp"
# Setup Info
dependencies = ["libssl3", "ca-certificates"]
# Deploy Info
deploy_dir = "./demo"
entrypoint = "./myapp"
pre_deploy_script = "./before-deploy.sh"
deploy_user = "deployman"
port_start = 3000
port_end = 3100
# Health Check
health_check_path = "/health"
health_check_timeout = 10
health_check_interval = 5
# Domain
domain = "myapp.localhost"
# Replicas
instances = 1
min_replicas = 1
max_replicas = 1
# ENV for myapp
[app.myapp.env]
APP_ENV = "simulation"
LOG_LEVEL = "debug"
APP_NAME = "myapp"
# Databases for myapp
[[app.myapp.database]]
databases = "mydb"
user = "u1"


[db.postgres]
enabled = true
version = "17"
replica_pass = "replica"

[db.postgres.backup]
full_backup_every = "1h"
incremental_backup_every = "15m"

[db.postgres.mydb]
name = "mydb"

[[db.postgres.users]]
state = "present"
user = "u1"
password = "u1"
databases = ["mydb"]


[backup.s3]
bucket = "crane1"
region = "us-east-1"
endpoint = "http://s3:9000"
access_key_id = "${S3_ACCESS_KEY_ID}"
secret_access_key = "${S3_SECRET_ACCESS_KEY}"


[domain]
provider = "cloudflare"
domain_name = "localhost"
token = "${CLOUDFLARE_TOKEN}"
