# crane.toml

[[nodes]]
name = "vps1"
host = "localhost"
public_ip = "localhost"
internal_ip = "10.0.0.11"
port = 2221
user = "admin"
roles = ["app", "traefik", "postgres", "redis"]

[[nodes]]
name = "vps2"
host = "localhost"
public_ip = "localhost"
internal_ip = "10.0.0.12"
port = 2222
user = "admin"
roles = ["app", "traefik", "postgres", "redis"]


[[nodes]]
name = "vps3"
host = "localhost"
public_ip = "localhost"
internal_ip = "10.0.0.13"
port = 2223
user = "admin"
roles = ["app", "traefik", "postgres", "redis"]


[[users]]
name = "deployman"
groups = ["www"]
ssh_authorized_keys = ["~/.ssh/id_rsa.pub"]


[app.myapp1]
name = "myapp"
# Deploy Info
deploy_dir = "./demo"
entrypoint = "./myapp"
deploy_user = "deployman"
port_start = 3000
port_end = 3100
instances = 1
dependencies = ["libssl3", "ca-certificates"]
# Health Check
health_check_path = "/health"
health_check_timeout = 30
health_check_interval = 2
# Domain
domain = "myapp.localhost"
# Keep old app versions
retain_releases = 3
# Replicas
min_replicas = 1
max_replicas = 3
# ENV for application
[app.myapp1.env]
APP_ENV = "simulation"
LOG_LEVEL = "debug"


[app.myapp2]
name = "myapp2"
# Deploy Info
deploy_dir = "./demo"
entrypoint = "./myapp"
deploy_user = "deployman"
port_start = 4000
port_end = 4100
instances = 1
dependencies = ["libssl3", "ca-certificates"]
# Health Check
health_check_path = "/health"
health_check_timeout = 30
health_check_interval = 2
# Domain
domain = "myapp2.localhost"
# Keep old app versions
retain_releases = 3
# Replicas
min_replicas = 1
max_replicas = 3
# ENV for application
[app.myapp2.env]
APP_ENV = "simulation"
LOG_LEVEL = "debug"


[domain]
provider = "cloudflare"
name = "localhost"
tls_email = "dev@example.com"


[db.postgres]
enabled = true
version = "17"

[[db.postgres.users]]
user = "app1"
password = "app1"
databases = ["myapp"]

[[db.postgres.users]]
user = "u2"
password = "u2"
databases = ["myapp"]

[db.postgres.myapp]
db_name = "myapp"


[db.redis]
enabled = true
version = "8"
bind = "127.0.0.1"


[backup.s3]
bucket = "crane1"
region = "us-east-1"
endpoint = "http://localhost:9000" # omit for AWS S3
# credentials in .env: S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY
# or specify here if not using .env
access_key_id = "miniominio"
secret_access_key = "miniominio"


[monitor]
interval = 30

[monitor.autoscale]
min_replicas = 1
max_replicas = 4
scale_up_cpu = 80
scale_down_cpu = 20
scale_up_memory = 85
cooldown = 120
