# crane.toml

[[nodes]]
name = "vps1"
host = "localhost"
public_ip = "10.0.0.11"
internal_ip = "10.0.0.11"
port = 2221
roles = ["app", "haproxy", "postgres", "redis"]
user = "crane"
private_key = "keys/id_ed25519"

[[nodes]]
name = "vps2"
host = "localhost"
public_ip = "10.0.0.12"
internal_ip = "10.0.0.12"
port = 2222
roles = ["app", "haproxy", "postgres", "redis"]
user = "crane"
private_key = "keys/id_ed25519"

[[nodes]]
name = "vps3"
host = "localhost"
public_ip = "10.0.0.13"
internal_ip = "10.0.0.13"
port = 2223
roles = ["app", "haproxy", "postgres", "redis"]
user = "crane"
private_key = "keys/id_ed25519"

[[users]]
name = "deployman"
groups = ["www"]
ssh_authorized_keys = ["keys/id_ed25519.pub"]
private_key = "keys/id_ed25519"

[app.myapp]
name = "myapp"
# Setup Info
dependencies = ["libssl3", "ca-certificates"]
# Deploy Info
deploy_dir = "./demo"
entrypoint = "./myapp"
pre_deploy_script = "./before-deploy.sh"
deploy_user = "deployman"
port_start = 3000
port_end = 3100
# Health Check
health_check_path = "/health"
health_check_timeout = 30
health_check_interval = 2
# Domain
domain = "myapp.localhost"
# Keep old app versions
retain_releases = 3
# Replicas
instances = 1
min_replicas = 1
max_replicas = 3

# ENV for application
[app.myapp.env]
APP_ENV = "simulation"
LOG_LEVEL = "debug"
APP_NAME = "myapp"

# Databases
[[app.myapp.database]]
databases = "mydb"
user = "u2"
[[app.myapp.database]]
databases = "mydb"
user = "u1"


[app.myapp2]
name = "myapp2"
# Setup Info
dependencies = ["libssl3", "ca-certificates"]
# Deploy Info
deploy_dir = "./demo"
entrypoint = "./myapp"
deploy_user = "deployman"
port_start = 4000
port_end = 4100
# Health Check
health_check_path = "/health"
health_check_timeout = 30
health_check_interval = 2
# Domain
domain = "myapp2.localhost"
# Keep old app versions
retain_releases = 3
# Replicas
instances = 1
min_replicas = 1
max_replicas = 3

# ENV for application
[app.myapp2.env]
APP_ENV = "simulation"
LOG_LEVEL = "debug"
APP_NAME = "myapp2"

# Databases
[[app.myapp2.database]]
databases = "mydb"
user = "u2"
[[app.myapp2.database]]
databases = "mydb"
user = "u1"


[db.postgres]
enabled = true
version = "17"

[db.postgres.backup]
full_backup_every = "1d"
incremental_backup_every = "1h"

[db.postgres.mydb]
name = "mydb"

[[db.postgres.users]]
# state = "present" / "absent"
state = "present"
user = "u1"
password = "u1"
databases = ["mydb"]

[[db.postgres.users]]
state = "present"
user = "u2"
password = "u2"
databases = ["mydb"]


#TODO: implement redis cluster deploy later
# [db.redis]
# enabled = true
# version = "8"
# bind = "127.0.0.1"


[backup.s3]
bucket = "crane1"
region = "us-east-1"
endpoint = "http://s3:9000" # omit for AWS S3
# credentials in .env: S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY
# or specify here if not using .env
access_key_id = "miniominio"
secret_access_key = "miniominio"

[domain]
provider = "cloudflare"
domain_name = "localhost"


[monitor]
interval = 30

[monitor.autoscale]
min_replicas = 1
max_replicas = 4
scale_up_cpu = 80
scale_down_cpu = 20
scale_up_memory = 85
cooldown = 120
